spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  sql:
    init:
      encoding: UTF-8

logging:
  level:
    org:
      springframework:
        security: DEBUG